[package]
name = "crayon"
version = "0.4.0"
authors = [ "Jingkai Mao <oammix@gmail.com>" ]
description = "An experimental entity-component-based multithread game engine."
repository = "https://github.com/shawnscode/crayon"
documentation = "http://docs.rs/crayon"
readme = "README.md"
license = "Apache-2.0"

keywords = ["ecs", "entity-component", "game-dev", "multithread"]
categories = ["game-engines", "multimedia"]

[badges]
travis-ci = { repository = "shawnscode/crayon", branch = "master" }
appveyor = { repository = "shawnscode/crayon", branch = "master", service = "github" }
codecov = { repository = "shawnscode/crayon", branch = "master", service = "github" }

[workspace]
members = [ "crayon-tools/workflow", "crayon-examples", "crayon-modules/imgui" ]

[dependencies]
gl = "0.10.0"
glutin = "0.17.0"
failure = "0.1.1"
crossbeam-deque = "0.5.1"
cgmath = "0.16.1"

[dev-dependencies]
rand = "0.5.4"
approx = "0.3.0"