[package]
name = "crayon-workflow"
version = "0.4.0"
authors = ["maojingkai <oammix@gmail.com>"]

[dependencies]
crayon = { path = "../..", version = "0.4.0" }
failure = "0.1.1"
image = "0.18.0"
uuid = { version = "0.6.5", features = ["v4"] }