[package]
name = "crayon-examples"
version = "0.4.0"
authors = ["Jingkai Mao <oammix@gmail.com>"]

[badges]
travis-ci = { repository = "shawnscode/crayon", branch = "master" }

[dependencies]
crayon = { path = "..", version = "0.4.0" }
crayon-imgui = { path = "../modules/imgui", version = "0.4.0" }
crayon-3d = { path = "../modules/3d", version = "0.4.0" }
failure = "0.1.1"
image = "0.18.0"
obj = "0.8.2"
rand = "0.4.2"